manifest:
  remotes:
    - name: yesitsfebreeze
      url-base: https://github.com/yesitsfebreeze
  projects:
    - name: zmk
      remote: yesitsfebreeze
      revision: main
      import: app/west.yml
  self:
    path: config